import type { Metadata } from "next";
import { Share_Tech } from 'next/font/google';
import "./globals.css";
import Navbar from "../components/Navbar";  

const shareTech = Share_Tech({ weight:'400', subsets:['latin'] });

export const metadata: Metadata = {
  title: "SDDC Official Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body className={shareTech.className}>
          <Navbar/>
          {children}
       </body>
    </html>
  );
}
