import type { Metadata } from 'next';
import { Share_Tech } from 'next/font/google';
import './globals.css';

const shareTech = Share_Tech({ weight:'400', subsets:['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={shareTech.className}>{children}</body>
    </html>
  );
}
