name: Build Next.js app
on: push
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js 20.14.x
        uses: actions/setup-node@v2
        with:
          node-version: '20.14.x'
      - name: Install dependencies
        run: npm install
      - name: Build website
        run: npm run build